name: Beacon
options:
  bundleIdPrefix: com.scifi
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  MSAL:
    url: https://github.com/AzureAD/microsoft-authentication-library-for-objc
    from: "1.3.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "7.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  PostgresNIO:
    url: https://github.com/vapor/postgres-nio
    from: "1.21.0"
  Yams:
    url: https://github.com/jpsim/Yams
    from: "6.0.0"
  AsyncAlgorithms:
    url: https://github.com/apple/swift-async-algorithms
    from: "1.0.0"

targets:
  Beacon:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Auth
      - path: Config
      - path: Models
      - path: Services
      - path: Utilities
      - path: ViewModels
      - path: Views
    dependencies:
      - package: MSAL
      - package: GoogleSignIn
      - package: KeychainAccess
      - package: KeyboardShortcuts
      - package: PostgresNIO
      - package: Yams
      - package: AsyncAlgorithms
    info:
      path: Info.plist
    entitlements:
      path: Beacon.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.scifi.beacon
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Beacon.entitlements
